[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2 --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
ENVIRONMENT = "production"
PYTHONPATH = "/app"
TOKENIZERS_PARALLELISM = "false"
OMP_NUM_THREADS = "2"
