services:
  - type: web
    name: customer-intelligence-ai-service
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
      - key: HF_XET_HIGH_PERFORMANCE
        value: "1"
      - key: MALLOC_ARENA_MAX
        value: "2"
