services:
  - type: web
    name: customer-intelligence-ai-service
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt  # Add this if needed
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2  # ← ADD THIS LINE
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
      - key: HF_XET_HIGH_PERFORMANCE
        value: "1"
      - key: MALLOC_ARENA_MAX
        value: "2"

